# Generated by Django 2.2.7 on 2019-12-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurantes',
            new_name='Restaurante',
        ),
    ]
