# Generated by Django 2.2.7 on 2019-12-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191209_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='categoria',
            field=models.CharField(choices=[('Celiacxs', 'Celiacxs'), ('Veganxs', 'Veganxs'), ('Vegetarianxs', 'Vegetarianxs')], default='categoria', max_length=100),
            preserve_default=False,
        ),
    ]
